<div class="footer_wrapper">
	<div class="footer">
        <div class="footer_sort footer_nvice"">
          <ul>
            <h2>新手入门</h2>
            <li><a href="/">购物流程</a></li>
            <li><a href="/">我的账户</a></li>
            <li><a href="/">交易条款</a></li>
          </ul>
        </div>
        <div class="footer_sort footer_distribution">
          <ul>
            <h2>配送方式</h2>
            <li><a href="/">配送说明</a></li>
            <li><a href="/">订单配送查询</a></li>
          </ul>
        </div>
        <div class="footer_sort footer_pay">
          <ul>
            <h2>支付方式</h2>
            <li><a href="/">货到付款</a></li>
          </ul>
        </div>
        <div class="footer_sort footer_aftermarket">
          <ul>
            <h2>售后服务</h2>
            <li><a href="/">退换货政策</a></li>
            <li><a href="/">退换货流程</a></li>
            <li><a href="/">退货申请</a></li>
            <li><a href="/">换货申请</a></li>
            <li><a href="/">申请余额提现</a></li>
          </ul>
        </div>
        <div class="footer_sort footer_characteristic">
          <ul>
            <h2>特色服务</h2>
            <li><a href="/">快速配送</a></li>
          </ul>
        </div>
        <div class="footer_sort footer_help">
          <ul>
            <h2>帮助信息</h2>
            <li><a href="/">常见问题</a></li>
            <li><a href="/">找回密码</a></li>
            <li><a href="/">退订邮件/短信</a></li>
            <li><a href="/">联系客服</a></li>
          </ul>
        </div>
      	<div style="clear: both;"></div>
      	
      	<div class="footer_pic">
	      <a href="http://support.dangdang.com/helpcenter/api_cms/helpcenter/question_sort/2242/180110.shtml" target="_blank" class="footer_pic01">正品保证 假一罚一</a>
	      <a class="footer_pic02" href="http://promo.dangdang.com/" target="_blank">一网打尽 更多优惠</a>
	      <a class="footer_pic03" href="http://blog.dangdang.com/?p=5770#ref=www-0-F" target="_blank">800城市货到付款 北上广深当日达</a>
	      <a class="footer_pic04" href="http://support.dangdang.com/helpcenter/api_cms/helpcenter/question_sort/2242/179422.shtml" target="_blank">上门退货当场退款</a>
	    </div>
	    
		<div class="footer_nav">
			<a href="http://static.dangdang.com/topic/2227/176801.shtml" target="_blank">公司简介</a><span class="sep">|</span> <a
			href="http://ir.dangdang.com/" target="_blank">Investor Relations</a><span
			class="sep">|</span> <a
			href="http://static.dangdang.com/topic/contents/1119/2263.shtml"
			target="_blank">诚征英才</a><span class="sep">|</span> <a
			href="http://union.dangdang.com/" target="_blank">网站联盟</a><span
			class="sep">|</span> <a
			href="http://static.dangdang.com/topic/744/8251.shtml" target="_blank">百货招商</a><span
			class="sep">|</span> <a
			href="http://misc.dangdang.com/groupbuy/Default.aspx" target="_blank">团购</a><span
			class="sep">|</span> <a href="http://misc2.dangdang.com/mobile_spread/"
			target="_blank">手机当当</a><span class="sep">|</span> <a
			href="http://blog.dangdang.com/" target="_blank">官方Blog</a>
		</div>
		<div class="footer_copyright">
			<span>Copyright (C) fuwu800 2004-2011, AllRights Reserved</span><span class="sep">|</span>
			<span><a href="http://www.miibeian.gov.cn/" target="_blank">京ICP证041189号</a></span>
			<span><a href="http://static.dangdang.com/music/topic/847_10762.shtml" target="_blank">音像制品经营许可证 京音网8号</a></span>
			<span><a href="http://static.dangdang.com/gjlwdwbab.rar">京公网安备110101000001号</a></span>
			<div class="clear"></div>
		</div>
		<div class="footer_police">警方提示：诈骗手段不断翻新，仍需提防。凡接到陌生电话、短信及上网交易信息时，请您做到不听、不信、不转账、不汇款，立即拨打110。</div>
		<div class="footer_icon">
			<div class="validator">
				<a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img">
					<img src="http://img4.ddimg.cn/00012/2010/validate.gif">
				</a>
			</div>
			<div class="knet"> 
				<!-- 可信网站LOGO安装开始 -->				
				<a href="https://ss.cnnic.cn/verifyseal.dll?sn=2010091900100002234&amp;pa=2940051" tabindex="-1" id="urlknet" target="_blank">
					<img width="128" height="47" alt="可信网站" name="CNNIC_seal" border="true" src="http://img4.ddimg.cn/00012/2010/knetSealLogo.png" oncontextmenu="return false;" onclick="CNNIC_change('urlknet')">
				</a>
				<!-- 可信网站LOGO安装结束 -->
			</div>            
			<div class="bjwhzf"><a href="#" target="_blank" class="footer_img"><img src="images/footer_teyue.jpg"></a></div>
			<div class="clear"></div>

  		</div>
	</div>
</div>
