<div class="header_wrap">
<div class="head_operate">
<ul class="head_operate_nav">
	<li class="head_cart"><a href="javascript:AddToShoppingCart(0);">购物车<span
		id="cart_items_count" class="cart_num"></span></a></li>
	<li class="head_separate"></li>
	<li><a href="http://order.dangdang.com/myallorders.aspx"
		target="_blank">我的订单</a></li>
	<li class="head_separate"></li>
	<li class="head_mydd"><a
		href="http://my.dangdang.com/myhome/homepage.aspx" target="_blank"
		class="menu_btn" id="a_myddchannel"
		onmouseover="showgaoji('a_myddchannel','__ddnav_mydd')"
		onmouseout="hideotherchannel('a_myddchannel','__ddnav_mydd');">我的中心</a>
	<div class="head_mydd_panel"
		onmouseover="showgaoji('a_myddchannel','__ddnav_mydd')"
		onmouseout="hideotherchannel('a_myddchannel','__ddnav_mydd');"
		id="__ddnav_mydd" style="z-index: 1000; display: none;">
	<ul class="head_mydd_list">
		<li><a href="http://order.dangdang.com/myallorders.aspx"
			target="_blank">我的订单</a></li>
		<li><a href="http://account.dangdang.com/payhistory/mycoupons.aspx"
			target="_blank">购物礼券</a></li>
		<li><a href="http://my.dangdang.com/memberpoints/index.aspx"
			target="_blank">我的积分</a></li>
		<li><a
			href="http://customer.dangdang.com/wishlist/cust_wish_list.aspx"
			target="_blank">我的收藏</a></li>
	</ul>
	</div>
	</li>
	<li class="head_separate"></li>
	<li class="head_gcard"><a
		href="http://misc.dangdang.com/giftcard/GiftCardIndex.aspx"
		class="menu_btn" id="a_lipchannel"
		onmouseover="showgaoji('a_lipchannel','__ddnav_card');"
		onmouseout="hideotherchannel('a_lipchannel','__ddnav_card');"
		target="_blank">礼品卡</a>
	<div class="head_gcard_panel"
		onmouseover="showgaoji('a_lipchannel','__ddnav_card')"
		onmouseout="hideotherchannel('a_lipchannel','__ddnav_card');"
		id="__ddnav_card" style="z-index: 1000; display: none;">
	<ul class="head_gcard_list">
		<li><a href="http://misc.dangdang.com/giftcard/GiftCardIndex.aspx"
			target="_blank">购买</a></li>
		<li><a href="http://account.dangdang.com/payhistory/mymoney.aspx"
			target="_blank">激活</a></li>
		<li><a href="http://misc.dangdang.com/giftcard/GiftCard_tuangou.aspx"
			target="_blank">团购</a></li>
	</ul>
	</div>
	</li>
	<li class="head_separate"></li>
	<li class="head_help"><a href="http://support.dangdang.com/helpcenter/"
		class="menu_btn" id="a_help_panel"
		onmouseover="showgaoji('a_help_panel','__ddnav_help');"
		onmouseout="hideotherchannel('a_help_panel','__ddnav_help');"
		target="_blank">帮&nbsp;助</a>
	<div class="head_help_panel" style="z-index: 1000; display: none;"
		id="__ddnav_help"
		onmouseover="showgaoji('a_help_panel','__ddnav_help');"
		onmouseout="hideotherchannel('a_help_panel','__ddnav_help');">
	<ul class="head_help_list">
		<li><a
			href="http://support.dangdang.com/helpcenter/api_cms/helpcenter/index/index.shtml"
			target="_blank">自助服务</a></li>
		<li><a
			href="http://service.dangdang.com/feedback/newcomplaint.aspx?page=1"
			target="_blank">意见建议</a></li>
		<li><a
			href="http://service.dangdang.com/feedback/newcomplaint.aspx?page=2"
			target="_blank">投诉反馈</a></li>
		<li><a href="http://robot.dangdang.com/WebIm/forward?id=51236699"
			target="_blank">在线小fuwu800</a></li>
	</ul>
	</div>
	</li>
</ul>
<p id="nickname">欢迎光临fuwu800，请<a name="ddnav_login"
	href="https://login.dangdang.com/signin.aspx?returnurl=http%3A//www.dangdang.com/"
	target="_self" class="login_link">登录</a><a name="ddnav_register"
	href="https://login.dangdang.com/Register.aspx" target="_self"
	class="login_link">免费注册</a></p>
</div>

</div>